#!/usr/bin/with-contenv bash
if [ "$enableAudioScript" != "true" ]; then
	echo "Automatic Start Disabled, to enable set enableAudioScript=true"
	echo "Manually run using this command:"
	echo "bash /config/extended/scripts/Audio.sh"
	sleep infinity
fi

echo "Starting Audio.sh in 2 min..."
sleep 2m
for (( ; ; )); do
	if test -f "/config/scanneeded.pid"; then
		ScanPlex
		rm /config/scanneeded.pid
	fi
	let i++
	bash /config/extended/scripts/Audio.sh
	echo "Audio.sh script sleeping for $scriptInterval..."
	sleep $scriptInterval
done

exit

ScanPlex () {
	if [ "$scanHook" ]
	then
		curl -s -X POST "{$scanHook}"
	fi
}
